local:
  cpus: 8
  memory: 12288
  storage: 40g
  gpu_support: false
  use_overlay: false
  #vm_driver: virtualbox
  vm_driver: kvm2
  provider: minikube

remote:
  type: aws
  cluster_name: data-mill
  bucket_name: data-mill
  region: "us-east1"
  zones: "us-east1a"
  no_nodes: 2
  node_size: t2.medium