image:
  repository: upmcenterprises/elasticsearch-operator
  tag: 0.0.12
  pullPolicy: IfNotPresent
  #pullPolicy: Always
  #pullSecret:

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

rbac:
  enabled: true
