kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-data-minio
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/minio/"
