kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-data-minio
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard 
  hostPath:
          path: "/mnt/vda1/data/storage/"
