# this flavour is used for minimal datalake setup
# for instance when testing the gpu support on the cluster
project:
  k8s_namespace: data-mill
  proxy_port: 8088
  flavour: minio, pachyderm
  # k8s default config, can be overwritten with -t filename
  # k8s_default_config: default_uc.yaml
  # not necessary, since we provide the definition in this file
  # component default config, can be overwritten with -f filename
  component_default_config: config.yaml
  # set the data folder
  data_folder: data

local:
  cpus: 8
  memory: 16288
  storage: 60G
  gpu_support: true
  use_overlay: false
  provider: microk8s
  use_multipass: false
