kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: stos-sc-name
provisioner: kubernetes.io/storageos
parameters:
  # the name of the distributed capacity pool to provision the volume from, default should be present if not specified
  pool: default
  # description for the dynamically created volumes
  description: K8s volume created with StorageOS
  fsType: ext4
  adminSecretNamespace: default
  adminSecretName: storageos-secret
