replicaCount: 1

image:
  repository: "datamillcloud/mlflow"
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 5000
  containerport: 5000

mount:
  path: /mnt/mlflow_data
  pvc: mlflow-pvc

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
