# Default K8s config for microk8s
local:
  cpus: 8
  memory: 16288
  storage: 60G
  gpu_support: true
  use_overlay: false
  provider: microk8s

# example config for a remote k8s cluster on AWS
remote:
  provider: aws
  cluster_name: data-mill
  bucket_name: data-mill
  region: "us-east1"
  zones: "us-east1a"
  no_nodes: 2
  node_size: t2.medium
