apiVersion: v1
kind: Pod
metadata:
  name: print-greeting
spec:
  containers:
  - name: env-print-demo
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.4
    env:
    command: ["echo"]
    args: ["Angelo is stupid!!!"]
