# https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/preexisting-pd
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data-minio
spec:
  # It's necessary to specify "" as the storageClassName
  # so that the default storage class won't be used, see
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
  storageClassName: "standard"
  volumeName: pv-data-minio
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
